name: Compilar CriPakTools Corrigido

on:
  workflow_dispatch: # Permite que você clique em um botão para iniciar a compilação manualmente

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Baixar o código-fonte
      uses: actions/checkout@v4

    - name: Configurar o MSBuild
      uses: microsoft/setup-msbuild@v2
      
    - name: Compilar o Executável
      run: msbuild CriPakTools.sln /p:Configuration=Release /p:Platform="Any CPU"

    - name: Disponibilizar para Download (Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: CriPakTools-Corrigido
        path: |
          **/bin/Release/CriPakTools.exe
          **/bin/Release/*.dll
